datagrid:
    entityconfig-grid:
        type: orm
        source:
            acl_resource: oro_entityconfig_manage
            type: orm
            query:
                select:
                    - ce.id
                    - ce.className as name
                    - ce.className as module
                    - ce.updated
                from:
                    - { table: OroEntityConfigBundle:EntityConfigModel, alias: ce }
        columns:
            name:
                label: Name
                type: field
                frontend_type: string
            module:
                label: Module
                type: field
                frontend_type: string
            updated:
                label: Updated at
                type: field
                frontend_type: datetime

        properties:
            update_link:
                type: url
                route: oro_tag_update
                params:
                    - id
            search_link:
                type: url
                route: oro_tag_search
                params:
                    - id
            delete_link:
                type: url
                route: oro_api_delete_tag
                params:
                    - id
        sorters:
            columns:
                name:
                    data_name: t.name
                usage:
                    data_name: usage
            default:
                label: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC

        filters:
            columns:
                name:
                    type: string
                    data_name: t.name
                usage:
                    type: string
                    data_name: usage
