datagrid:
    entityconfig-grid:
        options:
            toolbarOptions:
                pageSize:
                    default_per_page: 50
        source:
            acl_resource: oro_entityconfig_manage
            type: orm
            query:
                select:
                    - ce.id
                    - ce.className as name
                    - ce.className as module
                    - ce.updated
                    - ce.mode
                from:
                    - { table: OroEntityConfigBundle:EntityConfigModel, alias: ce }
        columns:
            name:
                label: Name
                type: field
                frontend_type: string
            #@TODO module column should has "select" type
            module:
                label: Module
                type: field
                frontend_type: string
            updated:
                label: Updated at
                type: field
                frontend_type: datetime

        properties:
            update_link:
                type: url
                route: oro_entityconfig_update
                params:
                    - id
            view_link:
                type: url
                route: oro_entityconfig_view
                params:
                    - id
        actions:
            # @TODO check why those actions dont have ACL
            update:
                type: navigate
                label: Update
                icon: edit
                link: update_link
                rowAction: true
            view:
                type: navigate
                label: View
                icon: book
                link: view_link
            remove:
                type: delete
                label: View
                icon: book
                link: view_link
        sorters:
            columns:
                name:
                    data_name: name
                module:
                    data_name: module
                updated:
                    data_name: ce.updated
        filters:
            columns:
                # @TODO Add choices for filters
                name:
                    type: choice
                    data_name: name
                module:
                    type: choice
                    data_name: module
                updated:
                    type: datetime
                    data_name: ce.updated
