oro_entity_config:
    scope:                              entity

    entity:
        form:
            blocks:
                -
                    title:          Entity Config
                    subblocks:
                        - { title: Base }
                        - { title: Icon }
        items:
            label:
                grid:
                    type:               string
                    label:              'Label'
                    filter_type:        oro_grid_orm_string
                    required:           true
                    sortable:           true
                    filterable:         true
                    show_filter:        true
                form:
                    type:               text
                    block:              0
                    subblock:           0
                    options:
                        required:       true
            icon:
                grid:
                    type:               string
                    label:              'Icon'
                    filter_type:        oro_grid_orm_string
                    required:           true
                    sortable:           true
                    filterable:         true
                    show_filter:        true
                form:
                    type:               text
                    subblock:           1
                    options:
                        required:       true
            description:
                form:
                    type:               textarea
                    options:
                        required:       false