oro_entity_config:
    scope:                              entity

    entity:
        form:
            block_config:
                entity:
                    priority:           20
                    subblocks:
                        base:           ~
                        icon:
                            title:      Icon Setting
        items:
            label:
                grid:
                    type:               string
                    label:              'Label'
                    filter_type:        oro_grid_orm_string
                    required:           true
                    sortable:           true
                    filterable:         true
                    show_filter:        true
                form:
                    type:               text
                    options:
                        block:          entity
                        subblock:       base
                        required:       true
            icon:
                grid:
                    type:               string
                    label:              'Icon'
                    filter_type:        oro_grid_orm_string
                    required:           true
                    sortable:           true
                    filterable:         true
                    show_filter:        true
                form:
                    type:               text
                    options:
                        block:          entity
                        subblock:       icon
                        required:       true
            description:
                form:
                    type:               textarea
                    options:
                        block:          entity
                        required:       false