parameters:
    oro_entity_config.extension.config.class:                   Oro\Bundle\EntityConfigBundle\Form\Extension\ConfigFormExtension
    oro_entity_config.form.type.config.class:                   Oro\Bundle\EntityConfigBundle\Form\Type\ConfigType
services:
    oro_entity_config.extension.config:
        class: %oro_entity_config.extension.config.class%
        tags:
            - { name: form.type_extension, alias: form }

    oro_entity_config.form.type.config:
        class:                                                  %oro_entity_config.form.type.config.class%
        arguments:                                              [@oro_entity_config.config_manager]
        tags:
            - { name: form.type, alias: oro_entity_config_config_type }