parameters:
    oro_entity_config.importexport.data_converter.entity_field.class: Oro\Bundle\EntityConfigBundle\ImportExport\DataConverter\EntityFieldDataConverter
    oro_entity_config.importexport.normalizer.entity_field.class: Oro\Bundle\EntityConfigBundle\ImportExport\Serializer\EntityFieldNormalizer
    oro_entity_config.importexport.strategy.entity_field.add_or_replace.class: Oro\Bundle\EntityConfigBundle\ImportExport\Strategy\EntityFieldImportStrategy
    oro_entity_config.importexport.template_fixture.entity_field.class: Oro\Bundle\EntityConfigBundle\ImportExport\TemplateFixture\EntityFieldFixture
    oro_entity_config.importexport.writer.entity_field.class: Oro\Bundle\EntityConfigBundle\ImportExport\Writer\EntityFieldWriter

services:
    # Converter
    oro_entity_config.importexport.data_converter.entity_field:
        class: %oro_entity_config.importexport.data_converter.entity_field.class%
        arguments:
            - @oro_entity_extend.field_type_provider
            - @oro_entity_config.config_manager

    # Strategy
    oro_entity_config.importexport.strategy.entity_field.add_or_replace:
        class: %oro_entity_config.importexport.strategy.entity_field.add_or_replace.class%
        parent: oro_importexport.strategy.configurable_add_or_replace
        calls:
            - [setTranslator, [@translator]]

    # Template Fixture
    oro_entity_config.importexport.template_fixture.entity_field:
        class: %oro_entity_config.importexport.template_fixture.entity_field.class%
        arguments:
            - @oro_entity_extend.field_type_provider
        tags:
            - { name: oro_importexport.template_fixture }

    # Import processor
    oro_entity_config.importexport.processor.import.entity_field:
        parent: oro_importexport.processor.import_abstract
        calls:
             - [setDataConverter, [@oro_entity_config.importexport.data_converter.entity_field]]
             - [setStrategy, [@oro_entity_config.importexport.strategy.entity_field.add_or_replace]]
        tags:
            - { name: oro_importexport.processor, type: import, entity: %oro_entity_config.entity.entity_field.class%, alias: oro_entity_config_entity_field.add_or_replace }
            - { name: oro_importexport.processor, type: import_validation, entity: %oro_entity_config.entity.entity_field.class%, alias: oro_entity_config_entity_field.add_or_replace }

    # Export template
    oro_entity_config.importexport.processor.export_template.entity_field:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, [@oro_entity_config.importexport.data_converter.entity_field]]
        tags:
            - { name: oro_importexport.processor, type: export_template, entity: %oro_entity_config.entity.entity_field.class%, alias: oro_entity_config_entity_field }

    oro_entity_config.importexport.normalizer.entityfield:
        parent: oro_importexport.serializer.configurable_entity_normalizer
        class: %oro_entity_config.importexport.normalizer.entity_field.class%
        calls:
            - [setRegistry, [@doctrine]]
            - [setConfigManager, [@oro_entity_config.config_manager]]
            - [setConfigModelManager, [@oro_entity_config.config_model_manager]]
            - [setFieldTypeProvider, [@oro_entity_extend.field_type_provider]]
        tags:
            - { name: oro_importexport.normalizer, priority: 20 }

    oro_entity_config.importexport.writer.entity_field:
        class: %oro_entity_config.importexport.writer.entity_field.class%
        arguments:
            - @oro_entity_config.config_manager
            - @oro_entity_config.translation.helper
