oro_menu_config:
    items:
        entities_list:
            label: 'Entities Config'
            route: 'oro_entityconfig_index'
            extras:
                routes: ['oro_entityconfig*']

    tree:
        application_menu:
            children:
                system_tab:
                    children:
                        entities_list: ~

oro_titles:
    oro_entityconfig_index: Entities Config
