oro_menu_config:
    items:
        entities_list:
            label: 'oro.entity_config.menu.entities_list.label'
            route: 'oro_entityconfig_index'
            extras:
                position:    80
                routes:      ['oro_entityconfig*', 'oro_entityextend*']
                description: 'oro.entity_config.menu.entities_list.description'

    tree:
        application_menu:
            children:
                system_tab:
                    children:
                        entities_list: ~

oro_titles:
    oro_entityconfig_index: ~
    oro_entityconfig_view: '%%entityName%%'
    oro_entityconfig_update: '%%entityName%%'
    oro_entityconfig_field_update: '%%fieldName%% - %%entityName%%'
