parameters:
    oro_entity_config.config_manager.class:                     Oro\Bundle\EntityConfigBundle\ConfigManager
    oro_entity_config.cache.file_cache.class:                   Oro\Bundle\EntityConfigBundle\Cache\FileCache
    oro_entity_config.command.setup.class:                      Oro\Bundle\EntityConfigBundle\Command\SetupCommand

services:
    oro_entity_config.proxy.entity_manager:
        tags:
            - { name: oro_entity_config.lazy,  service: doctrine.orm.default_entity_manager}

    oro_entity_config.config_manager:
        class:                                                  %oro_entity_config.config_manager.class%
        arguments:
            - @oro_entity_config.metadata.annotation_metadata_factory
            - @oro_entity_config.proxy.entity_manager
            - %oro_entity_config.config.scopes%
        calls:
            - [setCache, [@oro_entity_config.cache.file_cache]]

    oro_entity_config.cache.file_cache:
        class:                                                  %oro_entity_config.cache.file_cache.class%
        arguments:                                              [%oro_entity_config.cache_dir.config%]
        public:                                                 false

    oro_entity_config.command:
        class:                                                  %oro_entity_config.command.setup.class%
        calls:
            - [setContainer, [@service_container]]
