parameters:
    oro_entity_config.config_manager.class:                     Oro\Bundle\EntityConfigBundle\Config\ConfigManager
    oro_entity_config.cache.cache.class:                        Oro\Bundle\EntityConfigBundle\Config\ConfigCache
    oro_entity_config.provider_bag.class:                       Oro\Bundle\EntityConfigBundle\Provider\ConfigProviderBag
    oro_entity_config.cache.file_cache.class:                   Oro\Bundle\EntityConfigBundle\Cache\FileCache
    oro_entity_config.command.setup.class:                      Oro\Bundle\EntityConfigBundle\Command\SetupCommand

services:
    oro_entity_config.link.entity_manager:
        tags:
            - { name: oro_service_link,  service: doctrine.orm.default_entity_manager }

    oro_entity_config.link.security_context:
        tags:
            - { name: oro_service_link,  service: security.context }

    oro_entity_config.link.provider_bag:
        tags:
            - { name: oro_service_link,  service: oro_entity_config.provider_bag }

    oro_entity_config.link.provider_bag.method:
        arguments:                                             ['rr', 'd']
        tags:
            - { name: oro_service_method,  service: oro_entity_config.provider_bag, method: testAction }

    oro_entity_config.config_manager:
        class:                                                  %oro_entity_config.config_manager.class%
        arguments:
            - @oro_entity_config.metadata.annotation_metadata_factory
            - @event_dispatcher
            - @oro_entity_config.link.provider_bag
            - @oro_entity_config.link.entity_manager
            - @oro_entity_config.link.security_context
        calls:
            - [setCache, [@oro_entity_config.cache.cache]]

    oro_entity_config.provider_bag:
        class:                                                  %oro_entity_config.provider_bag.class%

    oro_entity_config.cache.cache:
        class:                                                  %oro_entity_config.cache.cache.class%
        arguments:                                              [@oro_entity_config.cache.file_cache]

    oro_entity_config.cache.file_cache:
        parent: oro.cache.abstract
        calls:
            - [setNamespace, ['oro_entity_config.cache']]

    oro_entity_config.command:
        class:                                                  %oro_entity_config.command.setup.class%
        calls:
            - [setContainer, [@service_container]]
