Oro\Bundle\EntityConfigBundle\Entity\FieldConfigModel:
        constraints:
            - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [fieldName, entity]
        properties:
            fieldName:
                - NotBlank:  ~
                - Regex:
                    pattern: "/^[a-z]+[a-z0-9_]*$/"
                    message: Value is not valid. You can use only lower alphabetic symbols, underscore and numbers
                - Regex:
                    pattern: "/^id$/i"
                    match:   false
                    message: Value is not valid. You cann't use 'id' as field name
                - Length:
                    min:     2
                    max:     50
            type:
                - NotBlank:  ~

Oro\Bundle\EntityConfigBundle\Entity\EntityConfigModel:
        constraints:
            - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [className]
        properties:
            className:
                - NotBlank:  ~
                - Regex:
                    pattern: "/^[a-z]+[a-z0-9]*$/i"
                    message: Value is not valid. You can use only lower alphabetic symbols, underscore and numbers
                - Length:
                    min:     5
                    max:     50

