Oro\Bundle\EntityConfigBundle\Entity\FieldConfigModel:
        constraints:
            - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [fieldName, entity]
        properties:
            fieldName:
                - NotBlank:     ~
                - Length:
                    min:        2
                    max:        50
            type:
                - NotBlank:     ~
                - Choice:
                    choices:  [string, integer, smallint, bigint, boolean, decimal, date, time, datetime, text, float]
                    message:  Choose a valid Data Type.
