oro_entity:
    entity_alias_exclusions:
        - Oro\Bundle\EntityConfigBundle\Entity\ConfigLog
        - Oro\Bundle\EntityConfigBundle\Entity\ConfigLogDiff
        - Oro\Bundle\EntityConfigBundle\Entity\ConfigModelIndexValue
        - Oro\Bundle\EntityConfigBundle\Entity\EntityConfigModel
        - Oro\Bundle\EntityConfigBundle\Entity\FieldConfigModel
